{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ephemeral-operator.fullname" . }}
  labels:
    {{- include "ephemeral-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [namespaces, resourcequotas, limitranges]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [ephemeral.elementor.io]
    resources: [ephemeralenvironments, ephemeralservices]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [ephemeral.elementor.io]
    resources: [ephemeralenvironments/status, ephemeralservices/status]
    verbs: [get, update, patch]
  - apiGroups: [ephemeral.elementor.io]
    resources: [ephemeralenvironments/finalizers, ephemeralservices/finalizers]
    verbs: [update]
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [traefik.io]
    resources: [ingressroutes]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ephemeral-operator.fullname" . }}
  labels:
    {{- include "ephemeral-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ephemeral-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ephemeral-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
