//go:build !ignore_autogenerated

// Code generated by hand for ephemeral-operator. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *EphemeralEnvironment) DeepCopyInto(out *EphemeralEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new deep copy.
func (in *EphemeralEnvironment) DeepCopy() *EphemeralEnvironment {
	if in == nil {
		return nil
	}
	out := new(EphemeralEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *EphemeralEnvironment) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *EphemeralEnvironmentList) DeepCopyInto(out *EphemeralEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EphemeralEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new deep copy.
func (in *EphemeralEnvironmentList) DeepCopy() *EphemeralEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EphemeralEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *EphemeralEnvironmentList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *EphemeralEnvironmentSpec) DeepCopyInto(out *EphemeralEnvironmentSpec) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	out.Database = in.Database
	in.Ingress.DeepCopyInto(&out.Ingress)
	if in.IncludeCoreApps != nil {
		in, out := &in.IncludeCoreApps, &out.IncludeCoreApps
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceBudget)
		**out = **in
	}
}

// DeepCopy creates a new deep copy.
func (in *EphemeralEnvironmentSpec) DeepCopy() *EphemeralEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EphemeralEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.EntrypointRefs != nil {
		in, out := &in.EntrypointRefs, &out.EntrypointRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto copies the receiver into out.
func (in *EphemeralEnvironmentStatus) DeepCopyInto(out *EphemeralEnvironmentStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceStatusSummary, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new deep copy.
func (in *EphemeralEnvironmentStatus) DeepCopy() *EphemeralEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EphemeralEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *EphemeralService) DeepCopyInto(out *EphemeralService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new deep copy.
func (in *EphemeralService) DeepCopy() *EphemeralService {
	if in == nil {
		return nil
	}
	out := new(EphemeralService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *EphemeralService) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *EphemeralServiceList) DeepCopyInto(out *EphemeralServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EphemeralService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new deep copy.
func (in *EphemeralServiceList) DeepCopy() *EphemeralServiceList {
	if in == nil {
		return nil
	}
	out := new(EphemeralServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *EphemeralServiceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto copies the receiver into out.
func (in *EphemeralServiceStatus) DeepCopyInto(out *EphemeralServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new deep copy.
func (in *EphemeralServiceStatus) DeepCopy() *EphemeralServiceStatus {
	if in == nil {
		return nil
	}
	out := new(EphemeralServiceStatus)
	in.DeepCopyInto(out)
	return out
}
