---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeral-operator
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - namespaces
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ephemeral.elementor.io
  resources:
  - ephemeralenvironments
  - ephemeralservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ephemeral.elementor.io
  resources:
  - ephemeralenvironments/finalizers
  - ephemeralservices/finalizers
  verbs:
  - update
- apiGroups:
  - ephemeral.elementor.io
  resources:
  - ephemeralenvironments/status
  - ephemeralservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - traefik.io
  resources:
  - ingressroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
