name: Install Dependencies
description: Install Node & NPM dependencies
runs:
    using: composite
    steps:
        - name: Install Node.js 20.x
          uses: actions/setup-node@v4
          with:
              cache: npm
              node-version: 20.x

        - name: Install Deps
          shell: bash
          run: npm ci
